//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldSkills2Entities3 : DbContext
    {
        private static WorldSkills2Entities3 _context;
        public WorldSkills2Entities3()
            : base("name=WorldSkills2Entities3")
        {
        }
    
        public static WorldSkills2Entities3 GetContext() 
        {
            if (_context == null)
                _context = new WorldSkills2Entities3();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Divisions> Divisions { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<GroupVisits> GroupVisits { get; set; }
        public virtual DbSet<SingleVisits> SingleVisits { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
