//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleVisits
    {
        public int Id { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Purpose { get; set; }
        public int Division { get; set; }
        public int Employee { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Organization { get; set; }
        public string Note { get; set; }
        public System.DateTime Birthday { get; set; }
        public int PassportSeries { get; set; }
        public int PassportNumber { get; set; }
        public byte[] ClientPhoto { get; set; }
        public byte[] PassportPhoto { get; set; }
        public int ClientId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Divisions Divisions { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
